title: Yanira's Portfolio
theme: jekyll-theme-minimal
description: "Hello, my name is Yanira De Souza I am a junior at the University of Michigan-Ann Arbor. I am currently studying data science and robotics and want to build intelligent systems in all fields." 
                    
              
