title: Yanira's Portfolio
theme: jekyll-theme-minimal
description: "Hi, my name is Yanira De Souza, and I am a junior at the University of Michigan-Ann Arbor. I am currently studying data science and robotics with the goal of developing intelligent systems in a variety of industries." 
                    
              
